name: Build and publish images

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - tag: "8.4"
            php: "8.4"
          - tag: "8.3"
            php: "8.3"
          - tag: "8.2"
            php: "8.2"
          - tag: "8.1"
            php: "8.1"
          - tag: "8.0"
            php: "8.0"

    steps:
      - uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ${{ matrix.php }}
          tags: ocreaper/php-nvm:${{ matrix.tag }}
